### ISSUE TITLE
Particle effects

### ISSUE THREAD

**Issue by UrbanHelsing** [maakep/cgj2018#20]
- [ ] Blood particles when units die
- [ ] Level up 
- [ ] Critical hit

... and more, like projectiles and stuff.

**Comment by ProgHaj** [comment]
Ok, kollar på det. Några andra partikeleffekter?

**Comment by maakep** [comment]
Fick du till några partikeleffekter?

**Comment by ProgHaj** [comment]
Nope, kollar på det nu.
